default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mahmudpg
  password: mahmudpg

development:
  <<: *default
  database: railsad-devise-puactivity-3can_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: railsad-devise-puactivity-3can_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: railsad-devise-puactivity-3can_production
  username: mahmudpg
  password: <%= ENV['GOHUB_DATABASE_PASSWORD'] %>
